[package]
name = "simple-website"
version = "0.1.0"
authors = ["Delyan Dobrev <delqn.dobrev@gmail.com>"]

[dependencies]
rand = "0.4"
rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = "0.3.5"
serde = "1.0.27"
serde_derive = "1.0.27"
